<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>NosGm.DAL</RootNamespace>
    <AssemblyName>NosGm.DAL</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="favicon.ico" />
    <Content Include="nosgm-emulator-icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\NosGm.Domain\NosGm.Domain.csproj" />
    <ProjectReference Include="..\NosGm.DAL.DAO\NosGm.DAL.DAO.csproj" />
    <ProjectReference Include="..\NosGm.DAL.Interface\NosGm.DAL.Interface.csproj" />
    <ProjectReference Include="..\NosGm.Data\NosGm.Data.csproj" />
  </ItemGroup>
</Project>
