// SPDX-License-Identifier: MIT

namespace NosGM.Web.Localization;

public static partial class PortalText
{
    private static IReadOnlyDictionary<string, string> CreateZhCn() =>
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["site.title"] = "NosGM",
            ["nav.home"] = "首页",
            ["nav.news"] = "新闻",
            ["nav.status"] = "状态",
            ["nav.rankings"] = "排行榜",
            ["nav.download"] = "下载",
            ["language"] = "语言",
            ["hero.eyebrow"] = "社区的新基础",
            ["hero.title"] = "为不断成长的世界打造安全门户",
            ["hero.subtitle"] = "以快速、清晰、多语言的方式提供新闻、服务状态、排行榜和启动器。",
            ["hero.primary"] = "查看状态",
            ["hero.secondary"] = "了解启动器",
            ["security.title"] = "安全优先于装饰",
            ["security.body"] = "此公开阶段不接收密码、付款或管理操作。",
            ["features.title"] = "已经准备好的功能",
            ["feature.updates.title"] = "可验证更新",
            ["feature.updates.body"] = "启动器使用签名清单、SHA-256、暂存区和事务恢复。",
            ["feature.languages.title"] = "十种语言",
            ["feature.languages.body"] = "门户与启动器提供相同的语言覆盖。",
            ["feature.status.title"] = "受限的公开数据",
            ["feature.status.body"] = "状态、新闻和排行榜使用小型契约和请求限制。",
            ["latest.news"] = "最新新闻",
            ["view.all"] = "查看全部",
            ["server.status"] = "服务器状态",
            ["online.players"] = "在线玩家",
            ["services"] = "服务",
            ["service"] = "服务",
            ["state"] = "状态",
            ["players"] = "玩家",
            ["updated"] = "更新时间",
            ["rankings.title"] = "排行榜",
            ["rankings.body"] = "在连接授权 API 前使用安全的演示结果。",
            ["rank"] = "名次",
            ["player"] = "角色",
            ["level"] = "等级",
            ["hero.level"] = "英雄等级",
            ["reputation"] = "声望",
            ["ranking.combat"] = "战斗",
            ["ranking.reputation"] = "声望",
            ["ranking.hero"] = "英雄",
            ["download.title"] = "下载 NosGM Launcher",
            ["download.body"] = "安全启动器负责安装、修复、语言和签名更新。",
            ["download.unavailable"] = "在配置签名生产包之前，公开下载将保持关闭。",
            ["download.security"] = "此仓库不会包含专有客户端或私钥。",
            ["news.title"] = "新闻",
            ["news.body"] = "通过独立于游戏服务器的契约提供公开公告。",
            ["news.empty"] = "尚未发布新闻。",
            ["status.title"] = "服务状态",
            ["status.body"] = "不包含内部地址或敏感运行细节的汇总公开视图。",
            ["health.online"] = "在线",
            ["health.degraded"] = "受限",
            ["health.offline"] = "离线",
            ["footer"] = "NosGM 社区项目。原创公开门户，不继承商业资源。",
            ["demo.notice"] = "安全演示数据",
            ["client.version"] = "客户端版本",
            ["launcher.version"] = "启动器",
            ["error.title"] = "无法完成请求",
            ["error.body"] = "请求已安全停止，请稍后重试。",
        };
}
