// SPDX-License-Identifier: MIT

namespace NosGM.Web.Localization;

public static partial class PortalText
{
    private static IReadOnlyDictionary<string, string> CreateCs() =>
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["site.title"] = "NosGM",
            ["nav.home"] = "Domů",
            ["nav.news"] = "Novinky",
            ["nav.status"] = "Stav",
            ["nav.rankings"] = "Žebříček",
            ["nav.download"] = "Stáhnout",
            ["language"] = "Jazyk",
            ["hero.eyebrow"] = "Nový základ pro komunitu",
            ["hero.title"] = "Bezpečný portál pro stále rostoucí svět",
            ["hero.subtitle"] = "Novinky, stav služeb, žebříčky a launcher v rychlém, přehledném a vícejazyčném prostředí.",
            ["hero.primary"] = "Zobrazit stav",
            ["hero.secondary"] = "Prozkoumat launcher",
            ["security.title"] = "Bezpečnost před ozdobami",
            ["security.body"] = "Tato veřejná fáze nepřijímá hesla, platby ani administrativní akce.",
            ["features.title"] = "Co je již připraveno",
            ["feature.updates.title"] = "Ověřitelné aktualizace",
            ["feature.updates.body"] = "Launcher používá podepsané manifesty, SHA-256, staging a transakční obnovu.",
            ["feature.languages.title"] = "Deset jazyků",
            ["feature.languages.body"] = "Portál podporuje stejné jazyky jako launcher.",
            ["feature.status.title"] = "Omezená veřejná data",
            ["feature.status.body"] = "Stav, novinky a žebříčky používají malé kontrakty a omezení požadavků.",
            ["latest.news"] = "Nejnovější novinky",
            ["view.all"] = "Zobrazit vše",
            ["server.status"] = "Stav serveru",
            ["online.players"] = "Hráči online",
            ["services"] = "Služby",
            ["service"] = "Služba",
            ["state"] = "Stav",
            ["players"] = "Hráči",
            ["updated"] = "Aktualizováno",
            ["rankings.title"] = "Žebříček",
            ["rankings.body"] = "Bezpečná demonstrační data do připojení autorizovaného API.",
            ["rank"] = "Pořadí",
            ["player"] = "Postava",
            ["level"] = "Úroveň",
            ["hero.level"] = "Úroveň hrdiny",
            ["reputation"] = "Reputace",
            ["ranking.combat"] = "Boj",
            ["ranking.reputation"] = "Reputace",
            ["ranking.hero"] = "Hrdina",
            ["download.title"] = "Stáhnout NosGM Launcher",
            ["download.body"] = "Bezpečný launcher spravuje instalaci, opravu, jazyky a podepsané aktualizace.",
            ["download.unavailable"] = "Veřejné stahování zůstane uzavřené, dokud nebude nastaven podepsaný produkční balíček.",
            ["download.security"] = "Repozitář nebude obsahovat proprietární klient ani soukromý klíč.",
            ["news.title"] = "Novinky",
            ["news.body"] = "Veřejná oznámení poskytovaná smlouvou nezávislou na herním serveru.",
            ["news.empty"] = "Zatím nebyly zveřejněny žádné novinky.",
            ["status.title"] = "Stav služeb",
            ["status.body"] = "Souhrnný veřejný pohled bez interních adres a citlivých provozních detailů.",
            ["health.online"] = "Online",
            ["health.degraded"] = "Omezeno",
            ["health.offline"] = "Offline",
            ["footer"] = "Komunitní projekt NosGM. Originální portál bez zděděných komerčních prostředků.",
            ["demo.notice"] = "Bezpečná demonstrační data",
            ["client.version"] = "Verze klienta",
            ["launcher.version"] = "Launcher",
            ["error.title"] = "Požadavek se nepodařilo dokončit",
            ["error.body"] = "Požadavek byl bezpečně zastaven. Zkuste to později.",
        };
}
