// SPDX-License-Identifier: MIT

namespace NosGM.Web.Localization;

public static partial class PortalText
{
    private static IReadOnlyDictionary<string, string> CreateIt() =>
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["site.title"] = "NosGM",
            ["nav.home"] = "Home",
            ["nav.news"] = "Notizie",
            ["nav.status"] = "Stato",
            ["nav.rankings"] = "Classifica",
            ["nav.download"] = "Scarica",
            ["language"] = "Lingua",
            ["hero.eyebrow"] = "Una nuova base per la comunità",
            ["hero.title"] = "Un portale sicuro per un mondo in crescita",
            ["hero.subtitle"] = "Notizie, stato dei servizi, classifiche e launcher in un’esperienza veloce, chiara e multilingue.",
            ["hero.primary"] = "Vedi stato",
            ["hero.secondary"] = "Scopri il launcher",
            ["security.title"] = "Sicurezza prima delle decorazioni",
            ["security.body"] = "Questa fase pubblica non accetta password, pagamenti o azioni amministrative.",
            ["features.title"] = "Già pronto",
            ["feature.updates.title"] = "Aggiornamenti verificabili",
            ["feature.updates.body"] = "Il launcher usa manifesti firmati, SHA-256, staging e recupero transazionale.",
            ["feature.languages.title"] = "Dieci lingue",
            ["feature.languages.body"] = "Il portale condivide la copertura linguistica del launcher.",
            ["feature.status.title"] = "Dati pubblici limitati",
            ["feature.status.body"] = "Stato, notizie e classifiche usano contratti ridotti e limiti di richieste.",
            ["latest.news"] = "Ultime notizie",
            ["view.all"] = "Vedi tutto",
            ["server.status"] = "Stato del server",
            ["online.players"] = "Giocatori online",
            ["services"] = "Servizi",
            ["service"] = "Servizio",
            ["state"] = "Stato",
            ["players"] = "Giocatori",
            ["updated"] = "Aggiornato",
            ["rankings.title"] = "Classifica",
            ["rankings.body"] = "Risultati dimostrativi sicuri finché non sarà collegata un’API autorizzata.",
            ["rank"] = "Posizione",
            ["player"] = "Personaggio",
            ["level"] = "Livello",
            ["hero.level"] = "Livello eroe",
            ["reputation"] = "Reputazione",
            ["ranking.combat"] = "Combattimento",
            ["ranking.reputation"] = "Reputazione",
            ["ranking.hero"] = "Eroe",
            ["download.title"] = "Scarica NosGM Launcher",
            ["download.body"] = "Il launcher sicuro gestisce installazione, riparazione, lingue e aggiornamenti firmati.",
            ["download.unavailable"] = "Il download pubblico resterà chiuso finché non sarà configurato un pacchetto di produzione firmato.",
            ["download.security"] = "Nessun client proprietario o chiave privata sarà incluso in questo repository.",
            ["news.title"] = "Notizie",
            ["news.body"] = "Annunci pubblici forniti tramite un contratto indipendente dal server di gioco.",
            ["news.empty"] = "Nessuna notizia pubblicata.",
            ["status.title"] = "Stato dei servizi",
            ["status.body"] = "Vista pubblica aggregata senza indirizzi interni o dettagli operativi sensibili.",
            ["health.online"] = "Online",
            ["health.degraded"] = "Degradato",
            ["health.offline"] = "Offline",
            ["footer"] = "Progetto della comunità NosGM. Portale originale senza risorse commerciali ereditate.",
            ["demo.notice"] = "Dati dimostrativi sicuri",
            ["client.version"] = "Versione client",
            ["launcher.version"] = "Launcher",
            ["error.title"] = "Impossibile completare la richiesta",
            ["error.body"] = "La richiesta è stata interrotta in sicurezza. Riprova più tardi.",
        };
}
