// SPDX-License-Identifier: MIT

namespace NosGM.Web.Localization;

public static partial class PortalText
{
    private static IReadOnlyDictionary<string, string> CreateFr() =>
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["site.title"] = "NosGM",
            ["nav.home"] = "Accueil",
            ["nav.news"] = "Actualités",
            ["nav.status"] = "État",
            ["nav.rankings"] = "Classement",
            ["nav.download"] = "Télécharger",
            ["language"] = "Langue",
            ["hero.eyebrow"] = "Une nouvelle base pour la communauté",
            ["hero.title"] = "Un portail sûr pour un monde en croissance",
            ["hero.subtitle"] = "Actualités, état des services, classement et launcher dans une expérience rapide, claire et multilingue.",
            ["hero.primary"] = "Voir l’état",
            ["hero.secondary"] = "Découvrir le launcher",
            ["security.title"] = "La sécurité avant la décoration",
            ["security.body"] = "Cette phase publique ne reçoit aucun mot de passe, paiement ou action administrative.",
            ["features.title"] = "Déjà prêt",
            ["feature.updates.title"] = "Mises à jour vérifiables",
            ["feature.updates.body"] = "Le launcher utilise des manifestes signés, SHA-256, une zone de préparation et une récupération transactionnelle.",
            ["feature.languages.title"] = "Dix langues",
            ["feature.languages.body"] = "Le portail partage la couverture linguistique du launcher.",
            ["feature.status.title"] = "Données publiques limitées",
            ["feature.status.body"] = "État, actualités et classements utilisent de petits contrats et des limites de requêtes.",
            ["weekly.eyebrow"] = "Mise à jour technique · 10–17 août 2026",
            ["weekly.title"] = "Ce que nous avons amélioré cette semaine",
            ["weekly.body"] = "Ces changements sont intégrés à la branche principale et font partie de la base actuelle de NosGM.",
            ["weekly.grpc.body"] = "Configuration a terminé sa migration : gRPC est désormais sa seule autorité, avec mTLS, récupération et mises à jour typées.",
            ["weekly.performance.body"] = "Login et World évitent les attentes bloquantes pour l’authentification et les autorisations ; le réseau réutilise lots, chiffrement et snapshots.",
            ["weekly.autoloot.body"] = "Les objets des monstres arrivent directement dans l’inventaire lorsque c’est possible et respectent l’ordre de partage du groupe.",
            ["weekly.discord.body"] = "Le pont GM exige des signatures indépendantes, des listes d’acteurs autorisés, le moindre privilège, la rotation des clés et une protection anti-rejeu.",
            ["weekly.migration.body"] = "Configuration a quitté SCS. Les callbacks de communication restent en observation sûre ; le retrait complet de SCS n’est pas encore terminé.",
            ["weekly.inprogress"] = "EN COURS",
            ["weekly.source"] = "Résumé fondé sur les changements confirmés de la branche principale.",
            ["latest.news"] = "Dernières actualités",
            ["view.all"] = "Tout voir",
            ["server.status"] = "État du serveur",
            ["online.players"] = "Joueurs en ligne",
            ["services"] = "Services",
            ["service"] = "Service",
            ["state"] = "État",
            ["players"] = "Joueurs",
            ["updated"] = "Mis à jour",
            ["rankings.title"] = "Classement",
            ["rankings.body"] = "Résultats de démonstration sûrs avant la connexion d’une API autorisée.",
            ["rank"] = "Rang",
            ["player"] = "Personnage",
            ["level"] = "Niveau",
            ["hero.level"] = "Niveau héros",
            ["reputation"] = "Réputation",
            ["ranking.combat"] = "Combat",
            ["ranking.reputation"] = "Réputation",
            ["ranking.hero"] = "Héros",
            ["download.title"] = "Télécharger NosGM Launcher",
            ["download.body"] = "Le launcher sécurisé gère installation, réparation, langues et mises à jour signées.",
            ["download.unavailable"] = "Le téléchargement public restera fermé jusqu’à la configuration d’un paquet de production signé.",
            ["download.security"] = "Aucun client propriétaire ni clé privée ne sera inclus dans ce dépôt.",
            ["news.title"] = "Actualités",
            ["news.body"] = "Annonces publiques servies par un contrat indépendant du serveur de jeu.",
            ["news.empty"] = "Aucune actualité publiée.",
            ["status.title"] = "État des services",
            ["status.body"] = "Vue publique agrégée sans adresses internes ni détails opérationnels sensibles.",
            ["health.online"] = "En ligne",
            ["health.degraded"] = "Dégradé",
            ["health.offline"] = "Hors ligne",
            ["footer"] = "Projet communautaire NosGM. Portail original sans ressources commerciales héritées.",
            ["demo.notice"] = "Données de démonstration sûres",
            ["client.version"] = "Version du client",
            ["launcher.version"] = "Launcher",
            ["error.title"] = "La requête n’a pas pu aboutir",
            ["error.body"] = "La requête a été arrêtée en sécurité. Réessayez plus tard.",
        };
}
