// SPDX-License-Identifier: MIT

namespace NosGM.Web.Localization;

public static partial class PortalText
{
    private static IReadOnlyDictionary<string, string> CreateEn() =>
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["site.title"] = "NosGM",
            ["nav.home"] = "Home",
            ["nav.news"] = "News",
            ["nav.status"] = "Status",
            ["nav.rankings"] = "Rankings",
            ["nav.download"] = "Download",
            ["language"] = "Language",
            ["hero.eyebrow"] = "A new foundation for the community",
            ["hero.title"] = "A secure portal for a world that keeps growing",
            ["hero.subtitle"] = "News, service status, rankings and the launcher in a fast, clear and multilingual experience.",
            ["hero.primary"] = "View status",
            ["hero.secondary"] = "Explore the launcher",
            ["security.title"] = "Security before decoration",
            ["security.body"] = "This public phase accepts no passwords, payments or administrative actions. Every sensitive feature will arrive with its own contracts and audit trail.",
            ["features.title"] = "What is already prepared",
            ["feature.updates.title"] = "Verifiable updates",
            ["feature.updates.body"] = "The launcher uses signed manifests, SHA-256, staging and transactional recovery.",
            ["feature.languages.title"] = "Ten languages",
            ["feature.languages.body"] = "The portal shares the launcher language coverage.",
            ["feature.status.title"] = "Bounded public data",
            ["feature.status.body"] = "Status, news and rankings use small contracts and request limits.",
            ["latest.news"] = "Latest news",
            ["view.all"] = "View all",
            ["server.status"] = "Server status",
            ["online.players"] = "Online players",
            ["services"] = "Services",
            ["service"] = "Service",
            ["state"] = "State",
            ["players"] = "Players",
            ["updated"] = "Updated",
            ["rankings.title"] = "Rankings",
            ["rankings.body"] = "Safe demonstration results until an authorized API is connected.",
            ["rank"] = "Rank",
            ["player"] = "Character",
            ["level"] = "Level",
            ["hero.level"] = "Hero level",
            ["reputation"] = "Reputation",
            ["ranking.combat"] = "Combat",
            ["ranking.reputation"] = "Reputation",
            ["ranking.hero"] = "Hero",
            ["download.title"] = "Download NosGM Launcher",
            ["download.body"] = "The secure launcher manages installation, repair, languages and signed updates.",
            ["download.unavailable"] = "Public download remains closed until a signed production package is configured.",
            ["download.security"] = "No proprietary client or private key will be included in this repository.",
            ["news.title"] = "News",
            ["news.body"] = "Public announcements served through a contract independent from the game server.",
            ["news.empty"] = "No news has been published yet.",
            ["status.title"] = "Service status",
            ["status.body"] = "Aggregated public view without internal addresses or sensitive operational details.",
            ["health.online"] = "Online",
            ["health.degraded"] = "Degraded",
            ["health.offline"] = "Offline",
            ["footer"] = "NosGM community project. Original public portal with no inherited commercial assets.",
            ["demo.notice"] = "Safe demonstration data",
            ["client.version"] = "Client version",
            ["launcher.version"] = "Launcher",
            ["error.title"] = "The request could not be completed",
            ["error.body"] = "The request was stopped safely. Please try again later.",
        };
}
