// SPDX-License-Identifier: MIT

namespace NosGM.Web.Localization;

public static partial class PortalText
{
    private static IReadOnlyDictionary<string, string> CreatePl() =>
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["site.title"] = "NosGM",
            ["nav.home"] = "Start",
            ["nav.news"] = "Aktualności",
            ["nav.status"] = "Status",
            ["nav.rankings"] = "Ranking",
            ["nav.download"] = "Pobierz",
            ["language"] = "Język",
            ["hero.eyebrow"] = "Nowa podstawa dla społeczności",
            ["hero.title"] = "Bezpieczny portal dla rozwijającego się świata",
            ["hero.subtitle"] = "Aktualności, status usług, rankingi i launcher w szybkim, przejrzystym i wielojęzycznym wydaniu.",
            ["hero.primary"] = "Zobacz status",
            ["hero.secondary"] = "Poznaj launcher",
            ["security.title"] = "Bezpieczeństwo przed ozdobami",
            ["security.body"] = "Ta publiczna faza nie przyjmuje haseł, płatności ani działań administracyjnych.",
            ["features.title"] = "Co jest już gotowe",
            ["feature.updates.title"] = "Weryfikowalne aktualizacje",
            ["feature.updates.body"] = "Launcher korzysta z podpisanych manifestów, SHA-256, stagingu i odzyskiwania transakcyjnego.",
            ["feature.languages.title"] = "Dziesięć języków",
            ["feature.languages.body"] = "Portal obsługuje te same języki co launcher.",
            ["feature.status.title"] = "Ograniczone dane publiczne",
            ["feature.status.body"] = "Status, aktualności i rankingi korzystają z małych kontraktów i limitów zapytań.",
            ["latest.news"] = "Najnowsze wiadomości",
            ["view.all"] = "Zobacz wszystko",
            ["server.status"] = "Status serwera",
            ["online.players"] = "Gracze online",
            ["services"] = "Usługi",
            ["service"] = "Usługa",
            ["state"] = "Stan",
            ["players"] = "Gracze",
            ["updated"] = "Zaktualizowano",
            ["rankings.title"] = "Ranking",
            ["rankings.body"] = "Bezpieczne dane demonstracyjne do czasu podłączenia autoryzowanego API.",
            ["rank"] = "Miejsce",
            ["player"] = "Postać",
            ["level"] = "Poziom",
            ["hero.level"] = "Poziom bohatera",
            ["reputation"] = "Reputacja",
            ["ranking.combat"] = "Walka",
            ["ranking.reputation"] = "Reputacja",
            ["ranking.hero"] = "Bohater",
            ["download.title"] = "Pobierz NosGM Launcher",
            ["download.body"] = "Bezpieczny launcher zarządza instalacją, naprawą, językami i podpisanymi aktualizacjami.",
            ["download.unavailable"] = "Publiczne pobieranie pozostanie zamknięte do czasu skonfigurowania podpisanego pakietu produkcyjnego.",
            ["download.security"] = "Repozytorium nie będzie zawierać zastrzeżonego klienta ani klucza prywatnego.",
            ["news.title"] = "Aktualności",
            ["news.body"] = "Publiczne ogłoszenia przez kontrakt niezależny od serwera gry.",
            ["news.empty"] = "Nie opublikowano jeszcze wiadomości.",
            ["status.title"] = "Status usług",
            ["status.body"] = "Zbiorczy widok publiczny bez adresów wewnętrznych i wrażliwych szczegółów.",
            ["health.online"] = "Online",
            ["health.degraded"] = "Ograniczony",
            ["health.offline"] = "Offline",
            ["footer"] = "Projekt społeczności NosGM. Oryginalny portal bez odziedziczonych zasobów komercyjnych.",
            ["demo.notice"] = "Bezpieczne dane demonstracyjne",
            ["client.version"] = "Wersja klienta",
            ["launcher.version"] = "Launcher",
            ["error.title"] = "Nie udało się wykonać żądania",
            ["error.body"] = "Żądanie zostało bezpiecznie zatrzymane. Spróbuj ponownie później.",
        };
}
