// SPDX-License-Identifier: MIT

namespace NosGM.Web.Localization;

public static partial class PortalText
{
    private static IReadOnlyDictionary<string, string> CreateEs() =>
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["site.title"] = "NosGM",
            ["nav.home"] = "Inicio",
            ["nav.news"] = "Noticias",
            ["nav.status"] = "Estado",
            ["nav.rankings"] = "Clasificación",
            ["nav.download"] = "Descargar",
            ["language"] = "Idioma",
            ["hero.eyebrow"] = "Una nueva base para la comunidad",
            ["hero.title"] = "Un portal seguro para un mundo que sigue creciendo",
            ["hero.subtitle"] = "Noticias, estado del servidor, clasificación y launcher en una experiencia rápida, clara y multilingüe.",
            ["hero.primary"] = "Ver estado",
            ["hero.secondary"] = "Conocer el launcher",
            ["security.title"] = "Seguridad antes que adornos",
            ["security.body"] = "Esta fase pública no recibe contraseñas, pagos ni acciones administrativas. Cada función sensible llegará con contratos y auditoría propios.",
            ["features.title"] = "Lo que ya está preparado",
            ["feature.updates.title"] = "Actualizaciones verificables",
            ["feature.updates.body"] = "El launcher usa manifiestos firmados, SHA-256, staging y recuperación transaccional.",
            ["feature.languages.title"] = "Diez idiomas",
            ["feature.languages.body"] = "La interfaz comparte la misma cobertura lingüística del launcher.",
            ["feature.status.title"] = "Datos públicos limitados",
            ["feature.status.body"] = "Estado, noticias y rankings se exponen mediante contratos pequeños y con límite de peticiones.",
            ["latest.news"] = "Últimas noticias",
            ["view.all"] = "Ver todo",
            ["server.status"] = "Estado del servidor",
            ["online.players"] = "Jugadores conectados",
            ["services"] = "Servicios",
            ["service"] = "Servicio",
            ["state"] = "Estado",
            ["players"] = "Jugadores",
            ["updated"] = "Actualizado",
            ["rankings.title"] = "Clasificación",
            ["rankings.body"] = "Resultados públicos de demostración hasta conectar un API autorizado.",
            ["rank"] = "Puesto",
            ["player"] = "Personaje",
            ["level"] = "Nivel",
            ["hero.level"] = "Nivel héroe",
            ["reputation"] = "Reputación",
            ["ranking.combat"] = "Combate",
            ["ranking.reputation"] = "Reputación",
            ["ranking.hero"] = "Héroe",
            ["download.title"] = "Descargar NosGM Launcher",
            ["download.body"] = "El launcher seguro administra instalación, reparación, idiomas y actualizaciones firmadas.",
            ["download.unavailable"] = "La descarga pública permanecerá cerrada hasta configurar un paquete de producción firmado.",
            ["download.security"] = "Nunca se incluirán el cliente propietario ni claves privadas en este repositorio.",
            ["news.title"] = "Noticias",
            ["news.body"] = "Anuncios públicos servidos desde un contrato independiente del servidor de juego.",
            ["news.empty"] = "Todavía no hay noticias publicadas.",
            ["status.title"] = "Estado de servicios",
            ["status.body"] = "Vista pública agregada, sin direcciones internas ni detalles operativos sensibles.",
            ["health.online"] = "En línea",
            ["health.degraded"] = "Degradado",
            ["health.offline"] = "Fuera de línea",
            ["footer"] = "Proyecto comunitario NosGM. Portal público original y sin recursos comerciales heredados.",
            ["demo.notice"] = "Datos de demostración seguros",
            ["client.version"] = "Versión del cliente",
            ["launcher.version"] = "Launcher",
            ["error.title"] = "No se pudo completar la solicitud",
            ["error.body"] = "La solicitud fue detenida de forma segura. Inténtalo nuevamente más tarde.",
        };
}
