// SPDX-License-Identifier: MIT

namespace NosGM.Web.Localization;

public static partial class PortalText
{
    private static IReadOnlyDictionary<string, string> CreateDe() =>
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["site.title"] = "NosGM",
            ["nav.home"] = "Start",
            ["nav.news"] = "Neuigkeiten",
            ["nav.status"] = "Status",
            ["nav.rankings"] = "Rangliste",
            ["nav.download"] = "Download",
            ["language"] = "Sprache",
            ["hero.eyebrow"] = "Eine neue Basis für die Community",
            ["hero.title"] = "Ein sicheres Portal für eine wachsende Welt",
            ["hero.subtitle"] = "Neuigkeiten, Serverstatus, Ranglisten und Launcher in einer schnellen, klaren und mehrsprachigen Oberfläche.",
            ["hero.primary"] = "Status ansehen",
            ["hero.secondary"] = "Launcher entdecken",
            ["security.title"] = "Sicherheit vor Dekoration",
            ["security.body"] = "Diese öffentliche Phase verarbeitet keine Passwörter, Zahlungen oder Verwaltungsaktionen.",
            ["features.title"] = "Bereits vorbereitet",
            ["feature.updates.title"] = "Prüfbare Updates",
            ["feature.updates.body"] = "Der Launcher nutzt signierte Manifeste, SHA-256, Staging und transaktionale Wiederherstellung.",
            ["feature.languages.title"] = "Zehn Sprachen",
            ["feature.languages.body"] = "Das Portal unterstützt dieselben Sprachen wie der Launcher.",
            ["feature.status.title"] = "Begrenzte öffentliche Daten",
            ["feature.status.body"] = "Status, Neuigkeiten und Ranglisten verwenden kleine Verträge und Anfragelimits.",
            ["latest.news"] = "Neueste Nachrichten",
            ["view.all"] = "Alle anzeigen",
            ["server.status"] = "Serverstatus",
            ["online.players"] = "Spieler online",
            ["services"] = "Dienste",
            ["service"] = "Dienst",
            ["state"] = "Status",
            ["players"] = "Spieler",
            ["updated"] = "Aktualisiert",
            ["rankings.title"] = "Rangliste",
            ["rankings.body"] = "Sichere Demodaten, bis eine autorisierte API verbunden ist.",
            ["rank"] = "Rang",
            ["player"] = "Charakter",
            ["level"] = "Level",
            ["hero.level"] = "Heldenlevel",
            ["reputation"] = "Ruf",
            ["ranking.combat"] = "Kampf",
            ["ranking.reputation"] = "Ruf",
            ["ranking.hero"] = "Held",
            ["download.title"] = "NosGM Launcher herunterladen",
            ["download.body"] = "Der sichere Launcher verwaltet Installation, Reparatur, Sprachen und signierte Updates.",
            ["download.unavailable"] = "Der öffentliche Download bleibt geschlossen, bis ein signiertes Produktionspaket konfiguriert ist.",
            ["download.security"] = "Kein proprietärer Client und kein privater Schlüssel wird in diesem Repository gespeichert.",
            ["news.title"] = "Neuigkeiten",
            ["news.body"] = "Öffentliche Ankündigungen über einen vom Spielserver getrennten Vertrag.",
            ["news.empty"] = "Noch keine Nachrichten veröffentlicht.",
            ["status.title"] = "Dienststatus",
            ["status.body"] = "Aggregierte öffentliche Ansicht ohne interne Adressen oder sensible Betriebsdetails.",
            ["health.online"] = "Online",
            ["health.degraded"] = "Eingeschränkt",
            ["health.offline"] = "Offline",
            ["footer"] = "NosGM Community-Projekt. Eigenständiges Portal ohne übernommene kommerzielle Assets.",
            ["demo.notice"] = "Sichere Demodaten",
            ["client.version"] = "Client-Version",
            ["launcher.version"] = "Launcher",
            ["error.title"] = "Die Anfrage konnte nicht abgeschlossen werden",
            ["error.body"] = "Die Anfrage wurde sicher beendet. Bitte später erneut versuchen.",
        };
}
