// SPDX-License-Identifier: MIT

namespace NosGM.Web.Localization;

public static partial class PortalText
{
    private static IReadOnlyDictionary<string, string> CreateJa() =>
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["site.title"] = "NosGM",
            ["nav.home"] = "ホーム",
            ["nav.news"] = "ニュース",
            ["nav.status"] = "状態",
            ["nav.rankings"] = "ランキング",
            ["nav.download"] = "ダウンロード",
            ["language"] = "言語",
            ["hero.eyebrow"] = "コミュニティの新しい基盤",
            ["hero.title"] = "成長し続ける世界のための安全なポータル",
            ["hero.subtitle"] = "ニュース、サービス状態、ランキング、ランチャーを高速で明確な多言語体験にまとめます。",
            ["hero.primary"] = "状態を見る",
            ["hero.secondary"] = "ランチャーを見る",
            ["security.title"] = "装飾より先に安全性",
            ["security.body"] = "この公開段階では、パスワード、決済、管理操作を受け付けません。",
            ["features.title"] = "すでに準備された機能",
            ["feature.updates.title"] = "検証可能な更新",
            ["feature.updates.body"] = "ランチャーは署名済みマニフェスト、SHA-256、ステージング、トランザクション復旧を使用します。",
            ["feature.languages.title"] = "10言語",
            ["feature.languages.body"] = "ポータルはランチャーと同じ言語範囲を提供します。",
            ["feature.status.title"] = "制限された公開データ",
            ["feature.status.body"] = "状態、ニュース、ランキングは小さな契約とリクエスト制限を使用します。",
            ["latest.news"] = "最新ニュース",
            ["view.all"] = "すべて見る",
            ["server.status"] = "サーバー状態",
            ["online.players"] = "オンライン人数",
            ["services"] = "サービス",
            ["service"] = "サービス",
            ["state"] = "状態",
            ["players"] = "プレイヤー",
            ["updated"] = "更新",
            ["rankings.title"] = "ランキング",
            ["rankings.body"] = "承認済みAPIに接続するまでの安全なデモ結果です。",
            ["rank"] = "順位",
            ["player"] = "キャラクター",
            ["level"] = "レベル",
            ["hero.level"] = "ヒーローレベル",
            ["reputation"] = "名声",
            ["ranking.combat"] = "戦闘",
            ["ranking.reputation"] = "名声",
            ["ranking.hero"] = "ヒーロー",
            ["download.title"] = "NosGM Launcherをダウンロード",
            ["download.body"] = "安全なランチャーがインストール、修復、言語、署名済み更新を管理します。",
            ["download.unavailable"] = "署名済み本番パッケージが設定されるまで公開ダウンロードは無効です。",
            ["download.security"] = "独自クライアントや秘密鍵をこのリポジトリに含めません。",
            ["news.title"] = "ニュース",
            ["news.body"] = "ゲームサーバーから独立した契約を通じて公開情報を提供します。",
            ["news.empty"] = "ニュースはまだありません。",
            ["status.title"] = "サービス状態",
            ["status.body"] = "内部アドレスや機密運用情報を含まない集約表示です。",
            ["health.online"] = "オンライン",
            ["health.degraded"] = "低下",
            ["health.offline"] = "オフライン",
            ["footer"] = "NosGMコミュニティプロジェクト。商用素材を継承しないオリジナル公開ポータルです。",
            ["demo.notice"] = "安全なデモデータ",
            ["client.version"] = "クライアント版",
            ["launcher.version"] = "ランチャー",
            ["error.title"] = "リクエストを完了できませんでした",
            ["error.body"] = "リクエストは安全に停止されました。後でもう一度お試しください。",
        };
}
