// SPDX-License-Identifier: MIT

namespace NosGM.Web.Localization;

public static partial class PortalText
{
    private static IReadOnlyDictionary<string, string> CreateRu() =>
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["site.title"] = "NosGM",
            ["nav.home"] = "Главная",
            ["nav.news"] = "Новости",
            ["nav.status"] = "Статус",
            ["nav.rankings"] = "Рейтинг",
            ["nav.download"] = "Скачать",
            ["language"] = "Язык",
            ["hero.eyebrow"] = "Новая основа для сообщества",
            ["hero.title"] = "Безопасный портал для растущего мира",
            ["hero.subtitle"] = "Новости, состояние сервисов, рейтинги и лаунчер в быстрой, понятной и многоязычной среде.",
            ["hero.primary"] = "Смотреть статус",
            ["hero.secondary"] = "О лаунчере",
            ["security.title"] = "Безопасность важнее украшений",
            ["security.body"] = "На этом публичном этапе нет паролей, платежей и административных действий.",
            ["features.title"] = "Что уже готово",
            ["feature.updates.title"] = "Проверяемые обновления",
            ["feature.updates.body"] = "Лаунчер использует подписанные манифесты, SHA-256, staging и транзакционное восстановление.",
            ["feature.languages.title"] = "Десять языков",
            ["feature.languages.body"] = "Портал поддерживает те же языки, что и лаунчер.",
            ["feature.status.title"] = "Ограниченные публичные данные",
            ["feature.status.body"] = "Статус, новости и рейтинги используют небольшие контракты и лимиты запросов.",
            ["latest.news"] = "Последние новости",
            ["view.all"] = "Показать все",
            ["server.status"] = "Статус сервера",
            ["online.players"] = "Игроки онлайн",
            ["services"] = "Сервисы",
            ["service"] = "Сервис",
            ["state"] = "Состояние",
            ["players"] = "Игроки",
            ["updated"] = "Обновлено",
            ["rankings.title"] = "Рейтинг",
            ["rankings.body"] = "Безопасные демонстрационные данные до подключения авторизованного API.",
            ["rank"] = "Место",
            ["player"] = "Персонаж",
            ["level"] = "Уровень",
            ["hero.level"] = "Уровень героя",
            ["reputation"] = "Репутация",
            ["ranking.combat"] = "Бой",
            ["ranking.reputation"] = "Репутация",
            ["ranking.hero"] = "Герой",
            ["download.title"] = "Скачать NosGM Launcher",
            ["download.body"] = "Безопасный лаунчер управляет установкой, восстановлением, языками и подписанными обновлениями.",
            ["download.unavailable"] = "Публичная загрузка будет закрыта до настройки подписанного производственного пакета.",
            ["download.security"] = "В репозитории не будет проприетарного клиента или закрытого ключа.",
            ["news.title"] = "Новости",
            ["news.body"] = "Публичные объявления через контракт, независимый от игрового сервера.",
            ["news.empty"] = "Новости пока не опубликованы.",
            ["status.title"] = "Состояние сервисов",
            ["status.body"] = "Обобщённый публичный вид без внутренних адресов и чувствительных деталей.",
            ["health.online"] = "Онлайн",
            ["health.degraded"] = "Ограничено",
            ["health.offline"] = "Оффлайн",
            ["footer"] = "Общественный проект NosGM. Оригинальный портал без унаследованных коммерческих ресурсов.",
            ["demo.notice"] = "Безопасные демонстрационные данные",
            ["client.version"] = "Версия клиента",
            ["launcher.version"] = "Лаунчер",
            ["error.title"] = "Не удалось выполнить запрос",
            ["error.body"] = "Запрос был безопасно остановлен. Повторите попытку позже.",
        };
}
