////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$Act4", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class Act4Packet : PacketDefinition
    {
        #region Properties
        
        public static string ReturnHelp() => "$Act4";

        #endregion
    }
}