////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$Act4Stat", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class Act4StatPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte Faction { get; set; }

        [PacketIndex(1)]
        public int Value { get; set; }

        public static string ReturnHelp() => "$Act4Stat <Faction> <Value>";

        #endregion
    }
}