////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$AddSkill", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class AddSkillPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public short SkillVNum { get; set; }

        public static string ReturnHelp() => "$AddSkill <VNum>";

        #endregion
    }
}