////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$Backpack", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class BackpackPacket : PacketDefinition
    {
        #region Methods

        public static string ReturnHelp() => "$Backpack";

        #endregion
    }
}