////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$BattlePass", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class BattlePassPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public int Type1 { get; set; }

        [PacketIndex(1)]
        public int Type2 { get; set; }

        [PacketIndex(2)]
        public int Type3 { get; set; }

        [PacketIndex(3)]
        public int Type4 { get; set; }
    }
}