////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$BazaarAudit", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public sealed class BazaarAuditPacket : PacketDefinition
    {
        [PacketIndex(0, SerializeToEnd = true)]
        public string Contents { get; set; }

        public static string ReturnHelp() =>
            "$BazaarAudit <status|recent|suspicious|listing|character|item> [value] [take]";
    }
}
