////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$Channel", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class ChannelPacket : PacketDefinition
    {

        [PacketIndex(0)]
        public byte ChannelID { get; set; }

        #region Properties

        public static string ReturnHelp() => "$Channel <ID>";

        #endregion
    }
}