////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$ChangeReputation", "$Reputation" , PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class ChangeReputationPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public long Reputation { get; set; }

        public static string ReturnHelp() => "$ChangeReputation | $Reputation <Value>";

        #endregion
    }
}