////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$CharEdit", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class CharacterEditPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string Property { get; set; }

        [PacketIndex(1, serializeToEnd: true)]
        public string Data { get; set; }

        public static string ReturnHelp() => "$CharEdit <Property> <Data>";

        #endregion
    }
}