////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$ClassPack", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class ClassPackPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public short Class { get; set; }

        public static string ReturnHelp() => "$ClassPack <ClassType[1 = Swordsman, 2 = Archer, 3 = Mage]>";

        #endregion
    }
}