////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$ClearMap", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class ClearMapPacket : PacketDefinition
    {
        #region Properties

        public static string ReturnHelp() => "$ClearMap";

        #endregion
    }
}