////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$CloneItem", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class CloneItemPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte Slot { get; set; }

        #endregion

        public static string ReturnHelp() => "$CloneItem <Slot>";
    }
}