////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$Demote", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class DemotePacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string CharacterName { get; set; }

        public static string ReturnHelp() => "$Demote <Nickname>";

        #endregion
    }
}