////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$Drops", PassNonParseablePacket = true, Authority = AuthorityType.User)]
    public class DropsPacket : PacketDefinition
    {
        #region Properties
        public static string ReturnHelp() => "$Drops";

        #endregion
    }
}