////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$FamilyFaction", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class FamilyFactionPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public string FamilyName { get; set; }

        public static string ReturnHelp() => "$FamilyFaction <Name>";
    }
}