////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$GlobalEvent", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class GlobalEventPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public EventType EventType { get; set; }

        public static string ReturnHelp() => "$GlobalEvent <Type>";

        #endregion
    }
}