////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$Home", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class HomePacket : PacketDefinition
    {
        #region Properties

        public static string ReturnHelp() => "$Home";

        #endregion
    }
}