////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$ItemTrace", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class ItemTracePacket : PacketDefinition
    {
        [PacketIndex(0, SerializeToEnd = true)]
        public string Contents { get; set; }

        public static string ReturnHelp() =>
            "$ItemTrace <item|serial|operation|duplicates|suspicious> <Guid?> [take]";
    }

    [PacketHeader("$StaffPerm", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class StaffPermissionPacket : PacketDefinition
    {
        [PacketIndex(0, SerializeToEnd = true)]
        public string Contents { get; set; }

        public static string ReturnHelp() =>
            "$StaffPerm <status|categories|show|enable|disable|grant|revoke> [account] [permission] [reason]";
    }
}
