////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$LeaveAct4", PassNonParseablePacket = true, Authority = AuthorityType.User)]
    public class LeaveAct4Packet : PacketDefinition
    {
        #region Properties
        
        public static string ReturnHelp() => "$LeaveAct4";

        #endregion
    }
}