////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$Lock", PassNonParseablePacket = true, Authority = AuthorityType.User)]
    public class LockCommandPacket : PacketDefinition
    {
        public int Code { get; set; }
    }
}