////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$ResetMap" , PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class MapResetPacket : PacketDefinition
    {
        #region Properties

        public static string ReturnHelp() => "$ResetMap";

        #endregion
    }
}