////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$MapStat", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class MapStatisticsPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public short? MapId { get; set; }

        #endregion

        #region Methods

        public static string ReturnHelp() => "$MapStat <?MapId>";

        #endregion
    }
}