////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$MonsterInfo", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class MonsterInfoPacket : PacketDefinition
    {
        public static string ReturnHelp() => "$MonsterInfo";
    }
}