////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$Morph", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class MorphPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public int MorphId { get; set; }

        [PacketIndex(1)]
        public byte Upgrade { get; set; }

        [PacketIndex(2)]
        public byte MorphDesign { get; set; }

        [PacketIndex(3)]
        public int ArenaWinner { get; set; }

        public static string ReturnHelp()
        {
            return "$Morph <VNum> <Upgrade> <Wings> <IsArenaWinner>";
        }

        #endregion
    }
}