////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$RaidboxInfo", PassNonParseablePacket = true, Authority = AuthorityType.User)]
    public class RaidboxInfoPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public string Type { get; set; }
    }
}