////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$Rarify", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class RarifyPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(1)]
        public RarifyMode Mode { get; set; }

        [PacketIndex(2)]
        public RarifyProtection Protection { get; set; }

        [PacketIndex(0)]
        public short Slot { get; set; }

        public static string ReturnHelp() => "$Rarify <Slot> <Mode> <Protection>";

        #endregion
    }
}