////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$Refresh", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class RefreshPacket : PacketDefinition
    {

    }
}