////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$Icon", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class ReputationIconPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public int Type { get; set; }
    }
}