////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$ReputationRate", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class ReputationRatePacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public int Value { get; set; }

        public static string ReturnHelp() => "$ReputationRate <Value>";

        #endregion
    }
}