////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$RestartAll", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class RestartAllPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public string WorldGroup { get; set; }

        [PacketIndex(1)]
        public int Time { get; set; }

        public static string ReturnHelp() => "$RestartAll <WorldGroup|*> <?Delay>";
    }
}