////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$Restart", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class RestartPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public int Time { get; set; }

        public static string ReturnHelp() => "$Restart <?Delay>";
    }
}