////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$SetReturnPoint", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class SetReturnPointPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte ReturnPointId { get; set; }

        #endregion

        #region Methods

        public static string ReturnHelp()
        {
            return "$SetReturnPoint RETURNPOINTID";
        }

        #endregion
    }
}