////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$SPRefill", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class SPRefillPacket : PacketDefinition
    {
        public static string ReturnHelp() => "$SPRefill";
    }
}