////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$TeleportToMe", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class SummonPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string CharacterName { get; set; }

        public static string ReturnHelp() => "$TeleportToMe <Nickname|*>";

        #endregion
    }
}