////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$Translate", PassNonParseablePacket = true, Authority = AuthorityType.User)]
    public class TranslatePacket : PacketDefinition
    {

        [PacketIndex(0)]
        public string From { get; set; }

        [PacketIndex(1)]
        public string To { get; set; }

        [PacketIndex(2, serializeToEnd: true)]
        public string Message { get; set; }

    }
}