////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$Usercount", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class UsercountPacket : PacketDefinition
    {
        #region Properties
        [PacketIndex(0)]
        public bool isStart { get; set; } = false;
        public static string ReturnHelp() => "$Usercount";

        #endregion
    }
}