////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.CommandPackets
{
    [PacketHeader("$Zoom", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class ZoomPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte Value { get; set; }

        public static string ReturnHelp() => "$Zoom <Value>";

        #endregion
    }
}