////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;

namespace Frostvein.Packets.Packets.ServerPackets
{
    [PacketHeader("act6")]
    public class Act6Packet : PacketDefinition
    {
        #region Properties

        #endregion
    }
}