////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;

namespace Frostvein.Packets.Packets.ServerPackets
{
    [PacketHeader("remove")]
    public class RemovePacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)] public byte EquipSlot { get; set; }

        [PacketIndex(1)] public long MateId { get; set; }

        #endregion
    }
}