<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <Platforms>x64;AnyCPU</Platforms>
    <RootNamespace>NosGm.GameObject</RootNamespace>
    <AssemblyName>NosGm.GameObject</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NosGm.Algorithm\NosGm.Algorithm.csproj" />
    <ProjectReference Include="..\NosGm.ChickenAPI\ChickenAPI.Events\ChickenAPI.Events.csproj" />
    <ProjectReference Include="..\NosGm.Configuration\NosGm.Configuration.csproj" />
    <ProjectReference Include="..\NosGm.Core\NosGm.Core.csproj" />
    <ProjectReference Include="..\NosGm.DAL\NosGm.DAL.Interface\NosGm.DAL.Interface.csproj" />
    <ProjectReference Include="..\NosGm.DAL\NosGm.DAL\NosGm.DAL.csproj" />
    <ProjectReference Include="..\NosGm.DAL\NosGm.Data\NosGm.Data.csproj" />
    <ProjectReference Include="..\NosGm.Domain\NosGm.Domain.csproj" />
    <ProjectReference Include="..\NosGm.Master.Library\NosGm.Master.Library.csproj" />
    <ProjectReference Include="..\NosGm.Packets\NosGm.Packets.csproj" />
    <ProjectReference Include="..\NosGm.PathFinder\NosGm.PathFinder.csproj" />
    <ProjectReference Include="..\NosGm.Program\NosGm.Logger\NosGm.LogServer.csproj" />
    <ProjectReference Include="..\NosGm.XMLModel\NosGm.XMLModel.csproj" />
    <ProjectReference Include="..\NosGm.AI\NosGm.AI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.8.1" />
    <PackageReference Include="Google.Cloud.Translation.V2" Version="3.5.0" />
    <PackageReference Include="log4net" Version="3.3.2" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.10.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Reactive" Version="6.1.0" />
    <PackageReference Include="WindowsFirewallHelper" Version="2.2.0.86" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Runtime.Caching" />
    <Reference Include="System.Web" />
    <Reference Include="WindowsBase" />
    <Reference Include="PresentationCore" />
    <Reference Include="System.Data.Entity" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
