////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$Automatic", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class AutomaticPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public byte Type { get; set; }

    }
}