////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$BlockPM", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class BlockPMPacket : PacketDefinition
    {
        public static string ReturnHelp() => "$BlockPM";
    }
}