////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$Buff", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class BuffPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public short CardId { get; set; }

        [PacketIndex(1)]
        public byte? Level { get; set; }

        #endregion

        #region Methods

        public static string ReturnHelp() => "$Buff <CardId> <?Level>";

        #endregion
    }
}