////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$ChangeSex", "$Sex" , PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class ChangeSexPacket : PacketDefinition
    {
        public static string ReturnHelp() => "$ChangeSex | $Sex";
    }
}