////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$ChangeShopName" , PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class ChangeShopNamePacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string Name { get; set; }

        public static string ReturnHelp() => "$ChangeShopName <Value>";

        #endregion
    }
}