////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$SPLvl", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class ChangeSpecialistLevelPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte SpecialistLevel { get; set; }

        public static string ReturnHelp() => "$SPLvl <Value>";

        #endregion
    }
}