////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$FLvl", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class ChangeFairyLevelPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public short FairyLevel { get; set; }

        public static string ReturnHelp() => "$FLvl <Value>";

        #endregion
    }
}