////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$ClearMap", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class ClearMapPacket : PacketDefinition
    {
        #region Properties

        public static string ReturnHelp() => "$ClearMap";

        #endregion
    }
}