////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$CI", "$CreateItem", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class CreateItemPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public short VNum { get; set; }

        [PacketIndex(1)]
        public short? Design { get; set; }

        [PacketIndex(2)]
        public byte? Upgrade { get; set; }

        public static string ReturnHelp() => "$CreateItem <VNum> <Design|Rare|Amount|Wings> <Upgrade>";

        #endregion

    }
}