////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$DisableNpc", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class DisableNpcPacket : PacketDefinition
    {
        public static string ReturnHelp() => "$DisableNpc";
    }
}