////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$Faction", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class FactionPacket : PacketDefinition
    {
        public static string ReturnHelp() => "$Faction";
    }
}