////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$Inspect", PassNonParseablePacket = true, Authority = AuthorityType.GS)]
    public sealed class PlayerInspectPacket : PacketDefinition
    {
        [PacketIndex(0, SerializeToEnd = true)]
        public string Contents { get; set; }

        public static string ReturnHelp() => "$Inspect <character|account> <id|name>";
    }

    [PacketHeader("$GmCase", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public sealed class GmCasePacket : PacketDefinition
    {
        [PacketIndex(0, SerializeToEnd = true)]
        public string Contents { get; set; }

        public static string ReturnHelp() =>
            "$GmCase <status|open|show|recent|mine|subject|note|evidence|assign|state|priority> ...";
    }
}