////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$Go" , PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class GogoPacket : PacketDefinition
    {
        #region Properties
        
        [PacketIndex(0)]
        public short X { get; set; }

        [PacketIndex(1)]
        public short Y { get; set; }

        public static string ReturnHelp() => "$Go <ToX> <ToY>";

        #endregion
    }
}