////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$ItemTrace", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class ItemTracePacket : PacketDefinition
    {
        [PacketIndex(0, SerializeToEnd = true)]
        public string Contents { get; set; }

        public static string ReturnHelp() =>
            "$ItemTrace <item|serial|operation|duplicates|suspicious> <Guid?> [take]";
    }
}
