////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$Kick", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class KickPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string CharacterName { get; set; }

        [PacketIndex(1)]
        public string Reason { get; set; }

        public static string ReturnHelp() => "$Kick <Nickname>";

        #endregion
    }
}