////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$Lock", PassNonParseablePacket = true, Authority = AuthorityType.User)]
    public class LockCommandPacket : PacketDefinition
    {
        public int Code { get; set; }
    }
}