////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$Music", PassNonParseablePacket = true, Authorities = new AuthorityType[] { AuthorityType.GM })]
    public class MusicPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public int Music { get; set; }

        public static string ReturnHelp() => "$Music BGM";

        #endregion
    }
}