////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$PenaltyLog", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class PenaltyLogPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string CharacterName { get; set; }

        public static string ReturnHelp() => "$PenaltyLog <Nickname>";

        #endregion
    }
}