////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$RemoveMonster", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class RemoveMobPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public string Code { get; set; }

        public static string ReturnHelp() => "$RemoveMonster";
    }
}