////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$Icon", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class ReputationIconPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public int Type { get; set; }
    }
}