////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$Sanction", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public sealed class SanctionPacket : PacketDefinition
    {
        [PacketIndex(0, SerializeToEnd = true)]
        public string Contents { get; set; }

        public static string ReturnHelp() =>
            "$Sanction <status|preview|confirm|cancel|recent> ...";
    }
}
