////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$ServerInfo", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class ServerInfoPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public int? ChannelId { get; set; }

        public static string ReturnHelp() => "$ServerInfo <?ChannelId>";
    }

    [PacketHeader("$Perf", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class PerformancePacket : PacketDefinition
    {
        [PacketIndex(0, SerializeToEnd = true)]
        public string Mode { get; set; }

        public static string ReturnHelp() => "$Perf <?runtime|packets|maps|security|reset|help>";
    }

    [PacketHeader("$GmAudit", PassNonParseablePacket = true, Authority = AuthorityType.ADMIN)]
    public class GmAuditPacket : PacketDefinition
    {
        [PacketIndex(0, SerializeToEnd = true)]
        public string Contents { get; set; }

        public static string ReturnHelp() =>
            "$GmAudit <recent|failed|account|character|command|status> <value?> [take]";
    }
}
