////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("$Sudo", PassNonParseablePacket = true, Authority = AuthorityType.DEV)]
    public class SudoPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public string CharacterName { get; set; }

        [PacketIndex(1, serializeToEnd: true)]
        public string CommandContents { get; set; }

        public static string ReturnHelp() => "$Sudo <Nickname> <Command>";
    }
}