////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.CommandPackets
{
    [PacketHeader("!", PassNonParseablePacket = true, Authority = AuthorityType.User)]
    public class TimeSpaceMessagePacket : PacketDefinition
    {

        [PacketIndex(0)]
        public string From { get; set; }

        [PacketIndex(1)]
        public string To { get; set; }

        [PacketIndex(2, serializeToEnd: true)]
        public string Message { get; set; }

    }
}