// <auto-generated />
namespace Frostvein.DAL.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class _03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_03));
        
        string IMigrationMetadata.Id
        {
            get { return "202607200130236_03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
