<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ApplicationIcon>nosgm-emulator-icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="nosgm-emulator-icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.9.0" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\NosGm.DAL\NosGm.DAL.Interface\NosGm.DAL.Interface.csproj" />
    <ProjectReference Include="..\..\NosGm.DAL\NosGm.Data\NosGm.Data.csproj" />
    <ProjectReference Include="..\..\NosGm.Domain\NosGm.Domain.csproj" />
    <ProjectReference Include="..\..\NosGm.GameObject\NosGm.GameObject.csproj" />
    <ProjectReference Include="..\..\NosGm.Packets\NosGm.Packets.csproj" />
  </ItemGroup>

</Project>
