<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
    <AssemblyName>NosGM.Launcher</AssemblyName>
    <RootNamespace>NosGM.Launcher</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NosGM.Updater.Core\NosGM.Updater.Core.csproj" />
  </ItemGroup>
</Project>
