<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>NosGm.PathFinder.Benchmark</RootNamespace>
    <AssemblyName>PathFinderBenchmark</AssemblyName>
    <LangVersion>7.3</LangVersion>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NosGm.PathFinder\NosGm.PathFinder.csproj" />
  </ItemGroup>
</Project>
