<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework Condition="'$(NosGmLegacyBuild)' == 'true'">net481</TargetFramework>
    <TargetFrameworks Condition="'$(NosGmLegacyBuild)' != 'true'">net481;net10.0</TargetFrameworks>
    <RootNamespace>ChickenAPI.DAL</RootNamespace>
    <AssemblyName>ChickenAPI.DAL</AssemblyName>
    <ApplicationIcon>nosgm-emulator-icon.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net481'">
    <Reference Include="System.ComponentModel.DataAnnotations" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="nosgm-emulator-icon.ico" />
  </ItemGroup>

</Project>
