////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.ClientPackets
{
    [PacketHeader("bp_open")]
    public class BpOpenPacket : PacketDefinition
    {

    }
}