////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;

namespace Frostvein.Packets.Packets.ClientPackets
{
    [PacketHeader("btk")]
    public class BtkPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)] 
        public long CharacterId { get; set; }

        [PacketIndex(1)]
        public string ReceiverName { get; set; }

        [PacketIndex(2, serializeToEnd: true)] 
        public string Message { get; set; }

        #endregion
    }
}