////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Core.Interfaces.Packets.ClientPackets;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.ClientPackets
{
    [PacketHeader("Char_NEW", IsCharScreen = true)]
    public class CharacterCreatePacket : PacketDefinition, ICharacterCreatePacket
    {
        #region Properties

        [PacketIndex(0)] public string Name { get; set; }

        [PacketIndex(1)] public byte Slot { get; set; }

        [PacketIndex(2)] public GenderType Gender { get; set; }

        [PacketIndex(3)] public HairStyleType HairStyle { get; set; }

        [PacketIndex(4)] public HairColorType HairColor { get; set; }

        public override string ToString() => $"Create Character Name: {Name} Slot: {Slot}";

        #endregion
    }
}