////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;

namespace Frostvein.Packets.Packets.ClientPackets
{
    [PacketHeader("compl")]
    public class ComplimentPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(1)] public long CharacterId { get; set; }

        #endregion
    }
}