////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;

namespace Frostvein.Packets.Packets.ClientPackets
{
    [PacketHeader("c_skill")]
    public class CSkillPacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}