////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.ClientPackets
{
    [PacketHeader("fauth")]
    public class FAuthPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)] public FamilyAuthority MemberType { get; set; }

        [PacketIndex(1)] public byte AuthorityId { get; set; }

        [PacketIndex(2)] public byte Value { get; set; }

        #endregion
    }
}