////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;

namespace Frostvein.Packets.Packets.ClientPackets
{
    [PacketHeader("f_stash_end")]
    public class FStashEndPacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}