////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.ClientPackets
{
    [PacketHeader("isort")]
    public class isortPacket : PacketDefinition
    {
        #region Properties


        [PacketIndex(0)]
        public InventoryType Type { get; set; }

        #endregion
    }
}