////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.ClientPackets
{
    [PacketHeader("put")]
    public class PutPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)] public InventoryType InventoryType { get; set; }

        [PacketIndex(1)] public byte Slot { get; set; }

        [PacketIndex(2)] public short Amount { get; set; }

        #endregion
    }
}