////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;

namespace Frostvein.Packets.Packets.ClientPackets
{
    [PacketHeader("shopclose")]
    public class ShopClosePacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}