////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;

namespace Frostvein.Packets.Packets.ClientPackets
{
    [PacketHeader("today_cts")]
    public class TodayPacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}