////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using Frostvein.Core;
using Frostvein.Domain;

namespace Frostvein.Packets.Packets.ClientPackets
{
    [PacketHeader("u_i")]
    public class UseItemPacket : PacketDefinition
    {
        [PacketIndex(2)] public InventoryType Type { get; set; }

        [PacketIndex(3)] public short Slot { get; set; }
    }
}