////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.ClientPackets
{
    [PacketHeader("bp_open")]
    public class BpOpenPacket : PacketDefinition
    {

    }
}