////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;

namespace NosGm.Packets.Packets.ClientPackets
{
    [PacketHeader("c_close")]
    public class CClosePacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}