////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;

namespace NosGm.Packets.Packets.ClientPackets
{
    [PacketHeader("dir")]
    public class DirectionPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(1)] public int Option { get; set; }

        [PacketIndex(0)] public byte Direction { get; set; }

        [PacketIndex(2)] public long CharacterId { get; set; }

        #endregion
    }
}