////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.ClientPackets
{
    [PacketHeader("req_exc")]
    public class ExchangeRequestPacket : PacketDefinition
    {
        [PacketIndex(0)] public RequestExchangeType RequestType { get; set; }

        [PacketIndex(1)] public long CharacterId { get; set; }
    }
}