////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.ClientPackets
{
    [PacketHeader("fmg")]
    public class FamilyManagementPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)] public FamilyAuthority FamilyAuthorityType { get; set; }

        [PacketIndex(1)] public long TargetId { get; set; }

        #endregion
    }
}