////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;

namespace NosGm.Packets.Packets.ClientPackets
{
    [PacketHeader("fhis_cts")]
    public class FhistCtsPacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}