////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;
using NosGm.Domain;

namespace NosGm.Packets.Packets.ClientPackets
{
    [PacketHeader("isort")]
    public class isortPacket : PacketDefinition
    {
        #region Properties


        [PacketIndex(0)]
        public byte Type { get; set; }

        #endregion
    }
}