////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;

namespace NosGm.Packets.Packets.ClientPackets
{
    [PacketHeader("m_shop")]
    public class MShopPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0, serializeToEnd: true)] // Todo: Find Value
        public string Data { get; set; }

        #endregion
    }
}