////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;

namespace NosGm.Packets.Packets.ClientPackets
{
    [PacketHeader("pleave")]
    public class PLeavePacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}