////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;

namespace NosGm.Packets.Packets.ClientPackets
{
    [PacketHeader("rxit")]
    public class RaidExitPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)] public byte State { get; set; }

        #endregion
    }
}