////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;

namespace NosGm.Packets.Packets.ClientPackets
{
    [PacketHeader("req_info")]
    public class ReqInfoPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)] public byte Type { get; set; }

        // Legacy requests use this field as a target VNum/slot/character id.
        // Modern type 6 requests use it as the entity type (1 character, 2 NPC/mate, 3 monster).
        [PacketIndex(1)] public long TargetTypeOrVNum { get; set; }

        // Present on modern type 6 requests and contains the entity transport id in the current map.
        [PacketIndex(2)] public int? TargetId { get; set; }

        #endregion
    }
}