////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosGm.Core;

namespace NosGm.Packets.Packets.ClientPackets
{
    [PacketHeader("select", IsCharScreen = true)]
    public class SelectPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)] public byte Slot { get; set; }

        #endregion
    }
}